entity_problem.entity_problem_type.*:
  type: config_entity
  label: 'Entity problem type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
