<?php

/**
 * @file
 * Contains pravdatut_party.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pravdatut_party_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pravdatut_party module.
    case 'help.page.pravdatut_party':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
