<?php

/**
 * @file
 * Contains social_auth_ext.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function social_auth_ext_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the social_auth_ext module.
    case 'help.page.social_auth_ext':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
