<?php

/**
 * @file
 * Contains paths_define.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function paths_define_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the paths_define module.
    case 'help.page.paths_define':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
