<?php

/**
 * @file
 * Contains gpb_services.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gpb_services_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gpb_services module.
    case 'help.page.gpb_services':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Services collection') . '</p>';
      return $output;

    default:
  }
}
